// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaxReXIR3H7n9tApAv7Ok1kXZdzbe0cqM',
    appId: '1:36534765797:web:12a22874f76b9074506c0c',
    messagingSenderId: '36534765797',
    projectId: 'vaulted-splice-370807',
    authDomain: 'vaulted-splice-370807.firebaseapp.com',
    storageBucket: 'vaulted-splice-370807.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0sFVbMWhfBtKGWACR6TY3A2jNCNr6BWk',
    appId: '1:36534765797:android:4c25d5ad0db36afa506c0c',
    messagingSenderId: '36534765797',
    projectId: 'vaulted-splice-370807',
    storageBucket: 'vaulted-splice-370807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM73YX-K7OS26P5Rd9yODaaG6hBhKrgTw',
    appId: '1:36534765797:ios:afac854ee817c539506c0c',
    messagingSenderId: '36534765797',
    projectId: 'vaulted-splice-370807',
    storageBucket: 'vaulted-splice-370807.appspot.com',
    iosClientId: '36534765797-o86eb4ldcc1crl49dvm2pvo1c19nj0aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab12',
  );
}
