// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-E36Cs-HYkFr8w1cHTAzIg0_-U1Vxkbc',
    appId: '1:314420035069:web:f3585b7a979b077de62d94',
    messagingSenderId: '314420035069',
    projectId: 'shatha-lab12',
    authDomain: 'shatha-lab12.firebaseapp.com',
    storageBucket: 'shatha-lab12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVAx4lx5Fcdh_-1OHvTp83GY6ij1lOwbU',
    appId: '1:314420035069:android:de7946829575264ae62d94',
    messagingSenderId: '314420035069',
    projectId: 'shatha-lab12',
    storageBucket: 'shatha-lab12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNbBLhJfjNOrutbZkv175f6IolNtnKIw',
    appId: '1:314420035069:ios:0b96c707c43a69dee62d94',
    messagingSenderId: '314420035069',
    projectId: 'shatha-lab12',
    storageBucket: 'shatha-lab12.appspot.com',
    iosClientId: '314420035069-jk4br4kqnlh1eni7k1lk0h2pp61d3655.apps.googleusercontent.com',
    iosBundleId: 'com.example.shathaLab12',
  );
}
