// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYU7HZxWSffX6Mkp_J7m3MWq99cta3_Yg',
    appId: '1:728905838882:web:213befb3dbda543558757b',
    messagingSenderId: '728905838882',
    projectId: 'flutter-lab12-7fc26',
    authDomain: 'flutter-lab12-7fc26.firebaseapp.com',
    storageBucket: 'flutter-lab12-7fc26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdq36fGCFa96Ac9H_u9l3XS7KxjDAMbPA',
    appId: '1:728905838882:android:30ef9e44a39444a858757b',
    messagingSenderId: '728905838882',
    projectId: 'flutter-lab12-7fc26',
    storageBucket: 'flutter-lab12-7fc26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHpdnEVEYENsXIx3rlcyowp-hyGdGxZ3M',
    appId: '1:728905838882:ios:a97b68482883968158757b',
    messagingSenderId: '728905838882',
    projectId: 'flutter-lab12-7fc26',
    storageBucket: 'flutter-lab12-7fc26.appspot.com',
    iosClientId: '728905838882-9m8536k1rrnofkr5pqjk79trgjsgrvjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hadeelLab12',
  );
}
